Makefile fix

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -9,12 +9,21 @@ has() {
 if [ ! -d ${DOT_DIR} ]; then
   if has "git"; then
     git clone https://github.com/natainakata/dotfiles.git ${DOT_DIR}
-  else 
-    wget https://github.com/natainakata/dotfiles/tarball/master
-    tar xvf master.tar.gz
+  elif has "curl" || has "wget"; then
+    TARBALL="https://github.com/natainakata/dotfiles/tarball/master.tar.gz"
+    if has "curl"; then
+      curl -L ${TARBALL} -o master.tar.gz
+    else
+      wget ${TARBALL}
+    fi
+    tar -zxvf master.tar.gz
     rm -f master.tar.gz
     mv -f dotfiles-master "${DOT_DIR}"
+  else
+    echo "curl or wget or git required"
+    exit 1
   fi
+  echo "Run make install"
 else
   echo "dotfiles already exists"
   exit 1
